/**
 * IncidentReportScreen — Auto-generated incident reports for police
 * Compiles: Location, time, recordings, SOS history, user profile data
 * Shareable as text or ready to send to authorities
 */
import React, { useState, useEffect } from 'react';
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity,
  Platform, Alert, TextInput, Share,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import * as FileSystem from 'expo-file-system';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useEmergency } from '../context/EmergencyContext';
import { useAuth } from '../context/AuthContext';
import { COLORS, SHADOWS } from '../constants/theme';

const REPORTS_KEY = '@gs_incident_reports';

export default function IncidentReportScreen() {
  const navigation = useNavigation();
  const { sosHistory, currentLocation, emergencyContacts } = useEmergency();
  const { userProfile } = useAuth();

  const [reports, setReports] = useState([]);
  const [generating, setGenerating] = useState(false);
  const [incidentDesc, setIncidentDesc] = useState('');
  const [showForm, setShowForm] = useState(false);

  useEffect(() => {
    loadReports();
  }, []);

  const loadReports = async () => {
    try {
      const data = await AsyncStorage.getItem(REPORTS_KEY);
      if (data) setReports(JSON.parse(data));
    } catch (e) {}
  };

  const saveReports = async (updated) => {
    setReports(updated);
    try {
      await AsyncStorage.setItem(REPORTS_KEY, JSON.stringify(updated));
    } catch (e) {}
  };

  // Generate comprehensive incident report
  const generateReport = async () => {
    if (!incidentDesc.trim()) {
      Alert.alert('Required', 'Please describe the incident briefly.');
      return;
    }

    setGenerating(true);

    const now = new Date();
    const loc = currentLocation;
    const locText = loc
      ? `Lat: ${loc.coords.latitude.toFixed(6)}, Lon: ${loc.coords.longitude.toFixed(6)}\nAccuracy: ${loc.coords.accuracy?.toFixed(0) || 'N/A'}m\nGoogle Maps: https://maps.google.com/?q=${loc.coords.latitude},${loc.coords.longitude}`
      : 'Location not available';

    // Count audio evidence files
    let audioCount = 0;
    try {
      const dir = FileSystem.documentDirectory;
      const files = await FileSystem.readDirectoryAsync(dir);
      audioCount = files.filter(f => f.endsWith('.m4a') || f.endsWith('.caf') || f.endsWith('.mp4')).length;
    } catch (e) {}

    const recentSOS = sosHistory.slice(0, 5).map((s, i) => 
      `  ${i + 1}. ${new Date(s.timestamp).toLocaleString()}${s.location ? ` — ${s.location.coords?.latitude.toFixed(4)}°, ${s.location.coords?.longitude.toFixed(4)}°` : ''}`
    ).join('\n') || '  None recorded';

    const contactsList = emergencyContacts.map((c, i) =>
      `  ${i + 1}. ${c.name} — ${c.phone} (Tier ${c.tier || 1})`
    ).join('\n') || '  No contacts configured';

    const reportText = `
═══════════════════════════════════════
    INCIDENT REPORT — GIRL SAFETY APP
═══════════════════════════════════════

Report ID: GS-${now.getTime().toString(36).toUpperCase()}
Generated: ${now.toLocaleString()}
App Version: 4.0

───────── VICTIM INFORMATION ─────────
Full Name: ${userProfile.fullName || 'Not provided'}
Phone: ${userProfile.phone || 'Not provided'}
Date of Birth: ${userProfile.dateOfBirth || 'Not provided'}
Gender: ${userProfile.gender || 'Not provided'}
Blood Group: ${userProfile.bloodGroup || 'Not provided'}

Medical Conditions: ${userProfile.medicalConditions || 'None specified'}
Allergies: ${userProfile.allergies || 'None specified'}
Medications: ${userProfile.medications || 'None specified'}

Home Address: ${userProfile.homeAddress || 'Not provided'}
Work/College: ${userProfile.workAddress || userProfile.collegeAddress || 'Not provided'}
Vehicle: ${userProfile.vehicleDetails || 'Not provided'}

────────── INCIDENT DETAILS ──────────
Date & Time: ${now.toLocaleString()}
Description: ${incidentDesc}

───────── LOCATION AT REPORT ─────────
${locText}

──────── RECENT SOS ACTIVATIONS ──────
${recentSOS}

──────── EMERGENCY CONTACTS ──────────
${contactsList}

────── EVIDENCE ON DEVICE ────────────
Audio Recordings: ${audioCount} file(s) stored locally
SOS History Entries: ${sosHistory.length}
Evidence Vault: Check app "Evidence Vault" for SHA-256 hashed logs

────────── LEGAL NOTICE ──────────────
This report was auto-generated by the Girl Safety App.
All timestamps are device-local time. Location data 
is GPS-based and may have accuracy variance.
Evidence files are stored with cryptographic hashes 
for tamper-proof verification.

For verification, contact app support or check the
Evidence Vault for SHA-256 integrity hashes.

═══════════════════════════════════════
    END OF REPORT
═══════════════════════════════════════
`.trim();

    const report = {
      id: now.getTime().toString(),
      createdAt: now.toISOString(),
      description: incidentDesc,
      location: loc ? {
        latitude: loc.coords.latitude,
        longitude: loc.coords.longitude,
      } : null,
      reportText,
      sosCount: sosHistory.length,
      audioCount,
    };

    const updated = [report, ...reports].slice(0, 20);
    await saveReports(updated);

    setGenerating(false);
    setShowForm(false);
    setIncidentDesc('');

    // Offer to share immediately
    Alert.alert(
      '📋 Report Generated',
      'Your incident report is ready. Share it now?',
      [
        { text: 'Later', style: 'cancel' },
        {
          text: 'Share Now',
          onPress: () => shareReport(reportText),
        },
      ]
    );
  };

  const shareReport = async (text) => {
    try {
      await Share.share({
        message: text,
        title: 'Girl Safety — Incident Report',
      });
    } catch (e) {
      Alert.alert('Error', 'Failed to share report');
    }
  };

  const deleteReport = (id) => {
    Alert.alert('Delete Report', 'Remove this incident report?', [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Delete', style: 'destructive',
        onPress: async () => {
          const updated = reports.filter(r => r.id !== id);
          await saveReports(updated);
        },
      },
    ]);
  };

  const formatDate = (iso) => {
    const d = new Date(iso);
    return d.toLocaleDateString() + ' ' + d.toLocaleTimeString();
  };

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backBtn}>
          <Ionicons name="arrow-back" size={24} color="#FFF" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Incident Report</Text>
        <TouchableOpacity onPress={() => setShowForm(!showForm)} style={styles.backBtn}>
          <Ionicons name={showForm ? 'close' : 'add-circle'} size={24} color="#FFF" />
        </TouchableOpacity>
      </View>

      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        {/* Info */}
        <View style={styles.infoBanner}>
          <Ionicons name="document-text" size={22} color="#4E342E" />
          <View style={{ flex: 1, marginLeft: 10 }}>
            <Text style={styles.infoTitle}>Police-Ready Reports</Text>
            <Text style={styles.infoText}>
              Auto-generates comprehensive incident reports with your location, time,
              profile info, SOS history, and evidence log. Ready to share with authorities.
            </Text>
          </View>
        </View>

        {/* New Report Form */}
        {showForm && (
          <View style={styles.formCard}>
            <Text style={styles.formTitle}>📝 New Incident Report</Text>
            <Text style={styles.formLabel}>Describe what happened:</Text>
            <TextInput
              style={styles.formInput}
              value={incidentDesc}
              onChangeText={setIncidentDesc}
              placeholder="e.g., Was followed by unknown person near..."
              placeholderTextColor={COLORS.textLight}
              multiline
              maxLength={500}
            />
            <Text style={styles.formHint}>
              The report will auto-include your location, profile, SOS history, and evidence data.
            </Text>
            <TouchableOpacity
              style={styles.generateBtn}
              onPress={generateReport}
              disabled={generating}
            >
              <Ionicons name="document-text" size={20} color="#FFF" />
              <Text style={styles.generateBtnText}>
                {generating ? 'Generating...' : 'Generate Report'}
              </Text>
            </TouchableOpacity>
          </View>
        )}

        {/* Stats */}
        <View style={styles.statsRow}>
          <View style={styles.statCard}>
            <Text style={styles.statNum}>{reports.length}</Text>
            <Text style={styles.statLabel}>Reports</Text>
          </View>
          <View style={styles.statCard}>
            <Text style={styles.statNum}>{sosHistory.length}</Text>
            <Text style={styles.statLabel}>SOS Events</Text>
          </View>
          <View style={styles.statCard}>
            <Text style={styles.statNum}>{emergencyContacts.length}</Text>
            <Text style={styles.statLabel}>Contacts</Text>
          </View>
        </View>

        {/* Reports List */}
        <Text style={styles.listTitle}>Generated Reports ({reports.length})</Text>
        {reports.length === 0 ? (
          <View style={styles.emptyState}>
            <Ionicons name="document-text-outline" size={48} color={COLORS.textLight} />
            <Text style={styles.emptyText}>No reports yet</Text>
            <Text style={styles.emptySubtext}>Tap + to create your first incident report</Text>
          </View>
        ) : (
          reports.map((report) => (
            <View key={report.id} style={styles.reportCard}>
              <View style={styles.reportHeader}>
                <Ionicons name="document-text" size={20} color="#4E342E" />
                <Text style={styles.reportDate}>{formatDate(report.createdAt)}</Text>
              </View>
              <Text style={styles.reportDesc} numberOfLines={2}>
                {report.description}
              </Text>
              <View style={styles.reportMeta}>
                <View style={styles.reportBadge}>
                  <Text style={styles.reportBadgeText}>
                    🚨 {report.sosCount} SOS
                  </Text>
                </View>
                <View style={styles.reportBadge}>
                  <Text style={styles.reportBadgeText}>
                    🎙️ {report.audioCount} Audio
                  </Text>
                </View>
                {report.location && (
                  <View style={styles.reportBadge}>
                    <Text style={styles.reportBadgeText}>📍 GPS</Text>
                  </View>
                )}
              </View>
              <View style={styles.reportActions}>
                <TouchableOpacity
                  style={styles.shareBtn}
                  onPress={() => shareReport(report.reportText)}
                >
                  <Ionicons name="share-outline" size={18} color={COLORS.primary} />
                  <Text style={styles.shareBtnText}>Share</Text>
                </TouchableOpacity>
                <TouchableOpacity
                  style={styles.deleteBtn}
                  onPress={() => deleteReport(report.id)}
                >
                  <Ionicons name="trash-outline" size={18} color="#FF1744" />
                </TouchableOpacity>
              </View>
            </View>
          ))
        )}

        {/* Helplines */}
        <View style={styles.helpSection}>
          <Text style={styles.helpTitle}>🏥 Post-Incident Support</Text>
          {[
            { label: 'Women Helpline', number: '1091', icon: 'woman' },
            { label: 'National Commission for Women', number: '7827170170', icon: 'call' },
            { label: 'Mental Health (iCall)', number: '9152987821', icon: 'heart' },
            { label: 'Legal Aid Services', number: '15100', icon: 'briefcase' },
          ].map((item, i) => (
            <TouchableOpacity key={i} style={styles.helpRow} onPress={() => {
              const { Linking } = require('react-native');
              Linking.openURL(`tel:${item.number.replace(/-/g, '')}`);
            }}>
              <Ionicons name={item.icon} size={18} color={COLORS.primary} />
              <Text style={styles.helpLabel}>{item.label}</Text>
              <Text style={styles.helpNum}>{item.number}</Text>
            </TouchableOpacity>
          ))}
        </View>

        <View style={{ height: 30 }} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.background },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 16, paddingTop: Platform.OS === 'ios' ? 60 : 48, paddingBottom: 18,
    backgroundColor: '#4E342E',
    borderBottomLeftRadius: 20, borderBottomRightRadius: 20,
  },
  backBtn: { padding: 8, backgroundColor: 'rgba(255,255,255,0.15)', borderRadius: 12 },
  headerTitle: { fontSize: 20, fontWeight: '800', color: '#FFF', letterSpacing: 0.3 },
  content: { padding: 16 },

  infoBanner: {
    flexDirection: 'row', backgroundColor: '#FFF8E1', borderRadius: 16, padding: 16,
    marginBottom: 16, alignItems: 'flex-start', borderWidth: 1, borderColor: '#FFE082',
  },
  infoTitle: { fontSize: 15, fontWeight: '800', color: '#4E342E' },
  infoText: { fontSize: 12, color: '#5D4037', marginTop: 4, lineHeight: 18 },

  // Form
  formCard: {
    backgroundColor: COLORS.surface, borderRadius: 20, padding: 20,
    marginBottom: 16, ...SHADOWS.medium, borderWidth: 1.5, borderColor: COLORS.primary + '25',
  },
  formTitle: { fontSize: 20, fontWeight: '800', color: COLORS.text, marginBottom: 14 },
  formLabel: { fontSize: 14, fontWeight: '700', color: COLORS.text, marginBottom: 8 },
  formInput: {
    backgroundColor: COLORS.background, borderRadius: 14, padding: 16,
    fontSize: 14, color: COLORS.text, minHeight: 120, textAlignVertical: 'top',
    borderWidth: 1, borderColor: COLORS.border, lineHeight: 20,
  },
  formHint: { fontSize: 11, color: COLORS.textLight, marginTop: 10, fontStyle: 'italic' },
  generateBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    backgroundColor: '#4E342E', borderRadius: 14, paddingVertical: 16, marginTop: 16,
    ...SHADOWS.small,
  },
  generateBtnText: { fontSize: 16, fontWeight: '800', color: '#FFF', marginLeft: 8, letterSpacing: 0.3 },

  // Stats
  statsRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
  statCard: {
    flex: 1, backgroundColor: COLORS.surface, borderRadius: 16, padding: 16,
    alignItems: 'center', marginHorizontal: 4, ...SHADOWS.small,
  },
  statNum: { fontSize: 28, fontWeight: '900', color: COLORS.primary },
  statLabel: { fontSize: 11, color: COLORS.textLight, marginTop: 4, fontWeight: '600' },

  listTitle: { fontSize: 16, fontWeight: '700', color: COLORS.text, marginBottom: 12 },

  emptyState: { alignItems: 'center', paddingVertical: 40 },
  emptyText: { fontSize: 16, fontWeight: '600', color: COLORS.textLight, marginTop: 12 },
  emptySubtext: { fontSize: 13, color: COLORS.textLight, marginTop: 4 },

  // Report Card
  reportCard: {
    backgroundColor: COLORS.surface, borderRadius: 16, padding: 16,
    marginBottom: 12, ...SHADOWS.small,
  },
  reportHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  reportDate: { fontSize: 13, fontWeight: '700', color: '#4E342E', marginLeft: 10 },
  reportDesc: { fontSize: 13, color: COLORS.text, marginBottom: 8, lineHeight: 18 },
  reportMeta: { flexDirection: 'row', marginBottom: 10 },
  reportBadge: {
    backgroundColor: '#EFEBE9', borderRadius: 8, paddingHorizontal: 10,
    paddingVertical: 4, marginRight: 8,
  },
  reportBadgeText: { fontSize: 11, fontWeight: '600', color: '#5D4037' },
  reportActions: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  shareBtn: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: COLORS.primary + '15',
    borderRadius: 8, paddingHorizontal: 14, paddingVertical: 8,
  },
  shareBtnText: { fontSize: 13, fontWeight: '600', color: COLORS.primary, marginLeft: 4 },
  deleteBtn: { padding: 8 },

  // Help
  helpSection: {
    backgroundColor: COLORS.surface, borderRadius: 16, padding: 18, marginTop: 16,
    ...SHADOWS.small,
  },
  helpTitle: { fontSize: 16, fontWeight: '700', color: COLORS.text, marginBottom: 12 },
  helpRow: {
    flexDirection: 'row', alignItems: 'center', paddingVertical: 10,
    borderBottomWidth: 1, borderBottomColor: COLORS.border,
  },
  helpLabel: { flex: 1, fontSize: 13, fontWeight: '500', color: COLORS.text, marginLeft: 10 },
  helpNum: { fontSize: 14, fontWeight: '700', color: COLORS.primary },
});
